# Generated by Django 6.0.2 on 2026-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
